from django.urls import path
from . import views

urlpatterns = [
    path('exam_view/', views.exam_view, name='exam_view'),
    path('download_template/', views.download_template, name='download_template'),
    path('check_course_students/', views.check_course_students, name='check_course_students'),
    path('submitGrades/', views.SubmitGradesView.as_view(), name='submitGrades'),
    path('upload_grades/', views.UploadGradesAPI.as_view(), name='upload_grades'),
    path('update_grades/', views.UpdateGradesAPI.as_view(), name='update_grades'),
    path('update_enter_grades/', views.UpdateEnterGradesAPI.as_view(), name='update_enter_grades'),
    path('moderate_student_grades/', views.ModerateStudentGradesAPI.as_view(), name='moderate_student_grades'),
    path('generate_transcript/', views.GenerateTranscript.as_view(), name='generate_transcript'),
    path('generate_transcript_form/', views.GenerateTranscriptForm.as_view(), name='generate_transcript_form'),
    path('generate_result/', views.GenerateResultAPI.as_view(), name='generate_result'),
    path('submit/', views.SubmitAPI.as_view(), name='submit'),
    path('download_excel/', views.DownloadExcelAPI.as_view(), name='download_excel'),
    path('submitGradesProf/', views.SubmitGradesProfAPI.as_view(), name='submitGradesProf'),
    path('upload_grades_prof/', views.UploadGradesProfAPI.as_view(), name='upload_grades_prof'),
    path('generate_pdf/', views.GeneratePDFAPI.as_view(), name='generate_pdf'),
    path('generate_student_result_pdf/', views.GenerateStudentResultPDFAPI.as_view(), name='generate_student_result_pdf'),
    path('downloadGrades/', views.DownloadGradesAPI.as_view(), name='downloadGrades'),
    path('verify_grades_dean/', views.VerifyGradesDeanView.as_view(), name='verify_grades_dean'),
    path('update_enter_grades_dean/', views.UpdateEnterGradesDeanView.as_view(), name='update_enter_grades_dean'),
    path('validate_dean/', views.ValidateDeanView.as_view(), name='validate_dean'),
    path('validate_dean_submit/', views.ValidateDeanSubmitView.as_view(), name='validate_dean_submit'),
    path('check_result/', views.CheckResultView.as_view(), name='check_result'),
    path('preview_grades/', views.PreviewGradesAPI.as_view(), name='preview_grades'),
    path('result-announcements/', views.ResultAnnouncementListAPI.as_view(), name='result-announcements'),
    path('update-announcement/', views.UpdateAnnouncementAPI.as_view(), name='update-announcement'),
    path('create-announcement/', views.CreateAnnouncementAPI.as_view(), name='create-announcement'),
    path('unique-course-reg-years/', views.UniqueRegistrationYearsView.as_view(), name='unique-course-reg-years'),
    path('unique-stu-grades-years/', views.UniqueStudentGradeYearsView.as_view(), name='unique-stu-grades-years'),
    path('student/result_semesters/', views.StudentSemesterListView.as_view(), name='get_student_semesters'),
    path('grade_status/', views.GradeStatusAPI.as_view(), name='grade_status'),
    path('grade_summary/', views.GradeSummaryAPI.as_view(), name='grade_summary'),
]
